<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.jmx.support.MBeanServerFactoryBeanTests" tests="7" skipped="0" failures="0" errors="0" timestamp="2021-03-04T16:40:06" hostname="WIN-LQAMLJ4MN5U" time="0.017">
  <properties/>
  <testcase name="newMBeanServer()" classname="org.springframework.jmx.support.MBeanServerFactoryBeanTests" time="0.001"/>
  <testcase name="createMBeanServer()" classname="org.springframework.jmx.support.MBeanServerFactoryBeanTests" time="0.0"/>
  <testcase name="locateExistingServerIfPossibleWithFallbackToPlatformServer()" classname="org.springframework.jmx.support.MBeanServerFactoryBeanTests" time="0.006"/>
  <testcase name="defaultDomain()" classname="org.springframework.jmx.support.MBeanServerFactoryBeanTests" time="0.0"/>
  <testcase name="withEmptyAgentIdAndFallbackToPlatformServer()" classname="org.springframework.jmx.support.MBeanServerFactoryBeanTests" time="0.007"/>
  <testcase name="defaultValues()" classname="org.springframework.jmx.support.MBeanServerFactoryBeanTests" time="0.001"/>
  <testcase name="locateExistingServerIfPossibleWithExistingServer()" classname="org.springframework.jmx.support.MBeanServerFactoryBeanTests" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[M?rz 05, 2021 12:40:06 VORM. ClientIntermediary close
INFO: java.io.IOException: The connection is not currently established.
java.io.IOException: The connection is not currently established.
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.checkState(ClientSynchroMessageConnectionImpl.java:617)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.sendOneWay(ClientSynchroMessageConnectionImpl.java:202)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:300)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:271)
	at javax.management.remote.generic.ClientIntermediary$GenericClientCommunicatorAdmin.doStop(ClientIntermediary.java:897)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.restart(ClientCommunicatorAdmin.java:172)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.gotIOException(ClientCommunicatorAdmin.java:73)
	at javax.management.remote.generic.GenericConnector$RequestHandler.execute(GenericConnector.java:662)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl$RemoteJob.run(ClientSynchroMessageConnectionImpl.java:568)
	at com.sun.jmx.remote.opt.util.ThreadService$ThreadServiceJob.run(ThreadService.java:248)
	at com.sun.jmx.remote.opt.util.JobExecutor.run(JobExecutor.java:99)

]]></system-err>
</testsuite>
